version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"  # Dependabot scans .github/workflows automatically
    schedule:
      interval: "monthly"
    groups:
      GitHub_Actions:
        patterns:
          - "*"  # Group all Actions updates into a single larger pull request

  # Enable version update for dev dependencies
  # Note: We cannot add any Python-based dependency here is because we require that dependency
  # to support the minimum Python supported by us (e.g. 3.10). But it is quite likely that
  # the dependency (e.g. numpy) would have upgraded their min Python version to say (e.g. 3.11)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "black"
    labels:
      - "dependencies"
