"""
Operations on quantum circuits.
"""

from .gates import (
    rx,
    ry,
    rz,
    sqrtnot,
    snot,
    phasegate,
    qrot,
    x_gate,
    y_gate,
    z_gate,
    cy_gate,
    cz_gate,
    s_gate,
    t_gate,
    qasmu_gate,
    cs_gate,
    ct_gate,
    cphase,
    cnot,
    csign,
    berkeley,
    swapalpha,
    swap,
    iswap,
    sqrtswap,
    sqrtiswap,
    fredkin,
    molmer_sorensen,
    toffoli,
    rotation,
    controlled_gate,
    globalphase,
    hadamard_transform,
    qubit_clifford_group,
    expand_operator,
    gate_sequence_product,
)

from .gateclass import (
    Gate,
    SingleQubitGate,
    TwoQubitGate,
    ControlledGate,
    ParametrizedGate,
    ControlledParamGate,
    ParametrizedSingleQubitGate,
    ParametrizedTwoQubitGate,
    CustomGate,
)
from .std_gates import (
    X,
    Y,
    Z,
    RX,
    RY,
    RZ,
    H,
    SNOT,
    SQRTNOT,
    S,
    T,
    R,
    QASMU,
    SWAP,
    ISWAP,
    SQRTSWAP,
    SQRTISWAP,
    SWAPALPHA,
    BERKELEY,
    MS,
    RZX,
    CX,
    CY,
    CZ,
    CRX,
    CRY,
    CRZ,
    CS,
    CT,
    CH,
    CNOT,
    CPHASE,
    CSIGN,
    CQASMU,
    TOFFOLI,
    FREDKIN,
    GLOBALPHASE,
    IDLE,
)
from .measurement import Measurement


GATE_CLASS_MAP: dict[str, Gate] = {
    "GLOBALPHASE": GLOBALPHASE,
    "IDLE": IDLE,
    "X": X,
    "Y": Y,
    "Z": Z,
    "RX": RX,
    "RY": RY,
    "RZ": RZ,
    "H": H,
    "SNOT": SNOT,
    "SQRTNOT": SQRTNOT,
    "S": S,
    "T": T,
    "R": R,
    "QASMU": QASMU,
    "SWAP": SWAP,
    "ISWAP": ISWAP,
    "iSWAP": ISWAP,
    "CNOT": CNOT,
    "SQRTSWAP": SQRTSWAP,
    "SQRTISWAP": SQRTISWAP,
    "SWAPALPHA": SWAPALPHA,
    "SWAPalpha": SWAPALPHA,
    "BERKELEY": BERKELEY,
    "MS": MS,
    "TOFFOLI": TOFFOLI,
    "FREDKIN": FREDKIN,
    "CSIGN": CSIGN,
    "CRX": CRX,
    "CRY": CRY,
    "CRZ": CRZ,
    "CX": CX,
    "CY": CY,
    "CZ": CZ,
    "CS": CS,
    "CT": CT,
    "CH": CH,
    "CPHASE": CPHASE,
    "RZX": RZX,
    "CQASMU": CQASMU,
}

__all__ = [
    "Gate",
    "SingleQubitGate",
    "TwoQubitGate",
    "ControlledGate",
    "ParametrizedGate",
    "ControlledParamGate",
    "ParametrizedSingleQubitGate",
    "ParametrizedTwoQubitGate",
    "CustomGate",
    "Measurement",
    "GATE_CLASS_MAP",
    "GLOBALPHASE",
    "rx",
    "ry",
    "rz",
    "sqrtnot",
    "snot",
    "phasegate",
    "qrot",
    "x_gate",
    "y_gate",
    "z_gate",
    "cy_gate",
    "cz_gate",
    "s_gate",
    "t_gate",
    "qasmu_gate",
    "cs_gate",
    "ct_gate",
    "cphase",
    "cnot",
    "csign",
    "berkeley",
    "swapalpha",
    "swap",
    "iswap",
    "sqrtswap",
    "sqrtiswap",
    "fredkin",
    "molmer_sorensen",
    "toffoli",
    "rotation",
    "controlled_gate",
    "globalphase",
    "hadamard_transform",
    "qubit_clifford_group",
    "expand_operator",
    "gate_sequence_product",
    "X",
    "Y",
    "Z",
    "RX",
    "RY",
    "RZ",
    "H",
    "SNOT",
    "SQRTNOT",
    "S",
    "T",
    "R",
    "QASMU",
    "SWAP",
    "ISWAP",
    "CNOT",
    "SQRTSWAP",
    "SQRTISWAP",
    "SWAPALPHA",
    "MS",
    "TOFFOLI",
    "FREDKIN",
    "BERKELEY",
    "CNOT",
    "CSIGN",
    "CRX",
    "CRY",
    "CRZ",
    "CY",
    "CX",
    "CZ",
    "CH",
    "CS",
    "CT",
    "CPHASE",
    "RZX",
    "CQASMU",
]
