from itertools import chain
from functools import reduce
from packaging.version import parse as parse_version
import numpy as np
import qutip


def _qobj_compatibility_helper(qobj):
    """
    Make qobj generated by operations in qutip-v5 identical to the one by qutip-v4.
    Here, if `qobj` is a number (e.g. generated by a bra-ket multiplication), it is replaced by a Qobj. 
    """
    if parse_version(qutip.__version__) >= parse_version("5.dev"):
        if np.isscalar(qobj):
            return qutip.Qobj([[qobj]], dims=[[1], [1]])
    return qobj
