name: Build HTML documentation
permissions:
  contents: read

on:
  push:
    paths: &trigger_paths
      - "doc/**"
      - "src/**.py"
      - ".github/workflows/build_documentation.yml" # Run when this exact pipeline file changes
      - "pyproject.toml" # Run when any dependency changes
  pull_request:
    paths: *trigger_paths

concurrency:
  group: doc_${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          
      - name: Install Pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc

      # Install in editable mode so it doesn't matter if we import from
      # inside the installation directory, otherwise we can get some errors
      # because we're importing from the wrong location.
      - name: Install qutip-qip and documentation dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[full] --group doc

      - name: Run qutip.about()
        shell: python
        run: |
          import qutip
          qutip.about()

      - name: Build documentation
        working-directory: doc
        run: |
          make html SPHINXOPTS="-W --keep-going -T"
          # Above flags are:
          #   -W : turn warnings into errors
          #   --keep-going : do not stop after the first error
          #   -T : display a full traceback if a Python exception occurs

      - name: Upload built files
        uses: actions/upload-artifact@v7
        with:
          name: qutip_qip_html_docs
          path: doc/_build/html/*
          if-no-files-found: error
