# Add the false positives in `.typos.toml` file.

name: Spelling check
on:
  push:
    branches: [ master, 'qutip-qip-*' ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v6

      - name: Spell Check the repo
        uses: crate-ci/typos@v1.45.1

  hyperlink:
    name: Check all hyperlinks
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo 
        uses: actions/checkout@v6

      - name: Restore lychee cache
        uses: actions/cache@v5
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-  # Just for fallback

      - name: Check all the hyperlinks
        uses: lycheeverse/lychee-action@v2
        with:
          args: --cache --max-cache-age 1d --extensions bib,md,rst,py,yaml,toml .
