name: Tests
permissions:
  contents: read

on:
  push:
    branches: [ master ]
    paths: &trigger_paths
      - "src/**/*.py"
      - "tests/**"
      - ".github/workflows/test.yaml" #Run when this exact pipeline file changes
      - "pyproject.toml" # Run when any dependency changes
  pull_request:
    paths: *trigger_paths

concurrency:
  group: test_${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  cases:
    name: ${{ matrix.os }}, python${{ matrix.python-version }}, ${{ matrix.case-name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Continue running jobs even if a previous job fails
      matrix:
        include:
          - case-name: windows
            os: windows-latest
            qutip-version: ''
            python-version: '3.10'

          - case-name: macOS
            os: macOS-latest
            qutip-version: ''
            python-version: '3.10'

          - case-name: linux
            os: ubuntu-latest
            qutip-version: ''
            python-version: '3.10'

          - case-name: qutip@5
            os: ubuntu-latest
            qutip-version: ''
            python-version: '3.11'

          - case-name: qutip@5
            os: ubuntu-latest
            qutip-version: ''
            python-version: '3.12'

          - case-name: qutip@5
            os: ubuntu-latest
            qutip-version: ''
            python-version: '3.13'

          - case-name: qutip@master
            os: ubuntu-latest
            qutip-version: '@master'
            python-version: '3.14'

    steps:
    - name: Clone the repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install QuTiP from PyPI
      if: ${{ matrix.qutip-version == ''}}
      run: python -m pip install 'qutip${{ matrix.qutip-version }}'

    - name: Install QuTiP from GitHub
      if: ${{ startsWith( matrix.qutip-version, '@') }}
      run: |
        pip install 'git+https://github.com/qutip/qutip.git${{ matrix.qutip-version }}'
        
    # Installing in-place so that coveralls can locate the source code.
    - name: Install qutip-qip
      run: |
        pip install --upgrade pip
        pip install -e .[full] --group test
        
    - name: Test with pytest and generate coverage report
      env:
        MPLBACKEND: Agg
      run: |
        pip install pytest-cov
        pytest tests --strict-markers --cov=qutip_qip --cov-report=lcov --color=yes

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        flag-name: run-${{ matrix.os }}-py${{ matrix.python-version }}-${{ matrix.case-name }}
        parallel: true

  finalise:
    name: Finalise coverage reporting
    needs: [cases]
    runs-on: ubuntu-latest
    steps:
      - name: Finalise coverage reporting
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
